version: '3'

services:
  database:
    build:
      context: ./docker/db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./var/cache/data:/var/lib/mysql

  php:
    build:
      context: ./docker/php
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - .:/srv/app

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/srv/app
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php
    ports:
      - "8080:80"
