version: '3'

services:
  php:
    build:
      context: ./docker/php
    env_file:
      - ./.env
    volumes:
      - .:/srv/app

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/srv/app
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php
    ports:
      - "8080:80"
