version: '3'

services:
  database:
    build:
      context: ./docker/db
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./var/cache/database:/var/lib/mysql

  php:
    build:
      context: ./docker/php
    depends_on:
      - database
    volumes:
      - .:/srv/app

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./var/log/nginx:/var/log/nginx
      - .:/srv/app
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"